export default {
  watch_history: [
                  {
                    id: 345534,
                    title: 'Game of Thrones',
                    original_title: 'Game of Thrones',
                    type: 'tv_series',
                    runtime_minutes: 60,
                    release_date: '2011-04-17',
                    genre_names: [ 'Action & Adventure', 'Drama', 'Sci-Fi & Fantasy' ],
                    user_rating: 8.9,
                    critic_score: 85,
                    us_rating: 'TV-MA',
                    poster: 'https://cdn.watchmode.com/posters/0345534_poster_w185.jpg',
                    original_language: 'en'
                  },
                  {
                    id: 1125474,
                    title: 'Eternal Sunshine of the Spotless Mind',
                    original_title: 'Eternal Sunshine of the Spotless Mind',
                    type: 'movie',
                    runtime_minutes: 108,
                    release_date: '2004-03-19',
                    genre_names: [ 'Drama', 'Romance', 'Science Fiction' ],
                    user_rating: 8.5,
                    critic_score: 91,
                    us_rating: 'R',
                    poster: 'https://cdn.watchmode.com/posters/01125474_poster_w185.jpg',
                    original_language: 'en'
                  },
                  {
                    id: 315551,
                    title: 'Boardwalk Empire',
                    original_title: 'Boardwalk Empire',
                    type: 'tv_series',
                    runtime_minutes: 60,
                    release_date: '2010-09-19',
                    genre_names: [ 'Crime', 'Drama' ],
                    user_rating: 8.6,
                    critic_score: 90,
                    us_rating: 'TV-MA',
                    poster: 'https://cdn.watchmode.com/posters/0315551_poster_w185.jpg',
                    original_language: 'en'
                  },
                  {
                    id: 1368011,
                    title: 'Synecdoche, New York',
                    original_title: 'Synecdoche, New York',
                    type: 'movie',
                    runtime_minutes: 124,
                    release_date: '2008-10-24',
                    genre_names: [ 'Drama' ],
                    user_rating: 7.4,
                    critic_score: 68,
                    us_rating: 'R',
                    poster: 'https://cdn.watchmode.com/posters/01368011_poster_w185.jpg',
                    original_language: 'en'
                  },
                  {
                    id: 3101216,
                    title: 'Rome',
                    original_title: 'Rome',
                    type: 'tv_series',
                    runtime_minutes: 60,
                    release_date: '2005-08-28',
                    genre_names: [ 'Action & Adventure', 'Drama' ],
                    user_rating: 8.8,
                    critic_score: 79,
                    us_rating: 'TV-MA',
                    poster: 'https://cdn.watchmode.com/posters/03101216_poster_w185.jpg',
                    original_language: 'en'
                  }
                ],
  watch_list: [
                {
                  id: 146796,
                  title: 'Being John Malkovich',
                  original_title: 'Being John Malkovich',
                  type: 'movie',
                  runtime_minutes: 113,
                  release_date: '1999-10-29',
                  genre_names: [ 'Comedy', 'Drama', 'Fantasy' ],
                  user_rating: 8.2,
                  critic_score: 92,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/0146796_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 1108602,
                  title: 'Donnie Darko',
                  original_title: 'Donnie Darko',
                  type: 'movie',
                  runtime_minutes: 114,
                  release_date: '2001-10-24',
                  genre_names: [ 'Drama', 'Fantasy', 'Mystery' ],
                  user_rating: 8.2,
                  critic_score: 87,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/01108602_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 3135512,
                  title: 'True Blood',
                  original_title: 'True Blood',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2008-09-07',
                  genre_names: [ 'Drama', 'Mystery', 'Sci-Fi & Fantasy' ],
                  user_rating: 7.7,
                  critic_score: 66,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/03135512_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 116597,
                  title: 'Adaptation.',
                  original_title: 'Adaptation.',
                  type: 'movie',
                  runtime_minutes: 115,
                  release_date: '2002-12-06',
                  genre_names: [ 'Comedy', 'Crime', 'Drama' ],
                  user_rating: 7.9,
                  critic_score: 87,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/0116597_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 392023,
                  title: 'Penny Dreadful',
                  original_title: 'Penny Dreadful',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2014-05-11',
                  genre_names: [ 'Drama', 'Mystery', 'Sci-Fi & Fantasy' ],
                  user_rating: 8.3,
                  critic_score: 81,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0392023_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 383653,
                  title: 'Narcos',
                  original_title: 'Narcos',
                  type: 'tv_series',
                  runtime_minutes: 57,
                  release_date: '2015-08-28',
                  genre_names: [ 'Crime', 'Drama' ],
                  user_rating: 8.7,
                  critic_score: 83,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0383653_poster_w185.jpg',
                  original_language: 'en'
                }
              ],
  all_items:  [
                {
                  id: 146796,
                  title: 'Being John Malkovich',
                  original_title: 'Being John Malkovich',
                  type: 'movie',
                  runtime_minutes: 113,
                  release_date: '1999-10-29',
                  genre_names: [ 'Comedy', 'Drama', 'Fantasy' ],
                  user_rating: 8.2,
                  critic_score: 92,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/0146796_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 1108602,
                  title: 'Donnie Darko',
                  original_title: 'Donnie Darko',
                  type: 'movie',
                  runtime_minutes: 114,
                  release_date: '2001-10-24',
                  genre_names: [ 'Drama', 'Fantasy', 'Mystery' ],
                  user_rating: 8.2,
                  critic_score: 87,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/01108602_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 3135512,
                  title: 'True Blood',
                  original_title: 'True Blood',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2008-09-07',
                  genre_names: [ 'Drama', 'Mystery', 'Sci-Fi & Fantasy' ],
                  user_rating: 7.7,
                  critic_score: 66,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/03135512_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 116597,
                  title: 'Adaptation.',
                  original_title: 'Adaptation.',
                  type: 'movie',
                  runtime_minutes: 115,
                  release_date: '2002-12-06',
                  genre_names: [ 'Comedy', 'Crime', 'Drama' ],
                  user_rating: 7.9,
                  critic_score: 87,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/0116597_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 392023,
                  title: 'Penny Dreadful',
                  original_title: 'Penny Dreadful',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2014-05-11',
                  genre_names: [ 'Drama', 'Mystery', 'Sci-Fi & Fantasy' ],
                  user_rating: 8.3,
                  critic_score: 81,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0392023_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 383653,
                  title: 'Narcos',
                  original_title: 'Narcos',
                  type: 'tv_series',
                  runtime_minutes: 57,
                  release_date: '2015-08-28',
                  genre_names: [ 'Crime', 'Drama' ],
                  user_rating: 8.7,
                  critic_score: 83,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0383653_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 345534,
                  title: 'Game of Thrones',
                  original_title: 'Game of Thrones',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2011-04-17',
                  genre_names: [ 'Action & Adventure', 'Drama', 'Sci-Fi & Fantasy' ],
                  user_rating: 8.9,
                  critic_score: 85,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0345534_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 1125474,
                  title: 'Eternal Sunshine of the Spotless Mind',
                  original_title: 'Eternal Sunshine of the Spotless Mind',
                  type: 'movie',
                  runtime_minutes: 108,
                  release_date: '2004-03-19',
                  genre_names: [ 'Drama', 'Romance', 'Science Fiction' ],
                  user_rating: 8.5,
                  critic_score: 91,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/01125474_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 315551,
                  title: 'Boardwalk Empire',
                  original_title: 'Boardwalk Empire',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2010-09-19',
                  genre_names: [ 'Crime', 'Drama' ],
                  user_rating: 8.6,
                  critic_score: 90,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/0315551_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 1368011,
                  title: 'Synecdoche, New York',
                  original_title: 'Synecdoche, New York',
                  type: 'movie',
                  runtime_minutes: 124,
                  release_date: '2008-10-24',
                  genre_names: [ 'Drama' ],
                  user_rating: 7.4,
                  critic_score: 68,
                  us_rating: 'R',
                  poster: 'https://cdn.watchmode.com/posters/01368011_poster_w185.jpg',
                  original_language: 'en'
                },
                {
                  id: 3101216,
                  title: 'Rome',
                  original_title: 'Rome',
                  type: 'tv_series',
                  runtime_minutes: 60,
                  release_date: '2005-08-28',
                  genre_names: [ 'Action & Adventure', 'Drama' ],
                  user_rating: 8.8,
                  critic_score: 79,
                  us_rating: 'TV-MA',
                  poster: 'https://cdn.watchmode.com/posters/03101216_poster_w185.jpg',
                  original_language: 'en'
                }
              ]
}

