const mockSearchResults = [{
  "id": 3173903,
  "title": "Breaking Bad",
  "original_title": "Breaking Bad",
  "plot_overview": "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
  "type": "tv_series",
  "runtime_minutes": 45,
  "year": 2008,
  "end_year": 2013,
  "release_date": "2008-01-20",
  "imdb_id": "tt0903747",
  "tmdb_id": 1396,
  "tmdb_type": "tv",
  "genres": [
      7
  ],
  "genre_names": [
      "Drama"
  ],
  "user_rating": 9.3,
  "critic_score": 85,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/03173903_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/03173903_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      3131293,
      3129354,
      383653,
      390224,
      313542,
      3124749,
      340865,
      350372,
      3109684,
      3130921,
      316177,
      345534,
      3158493,
      1122525,
      519834,
      3140350,
      383654,
      125583,
      3137595,
      3164525,
      3155583,
      350396,
      3129647,
      520325,
      329319
  ],
  "networks": [
      8
  ],
  "network_names": [
      "AMC"
  ],
  "relevance_percentile": 98.93,
  "trailer": "https://www.youtube.com/watch?v=XZ8daibM3AE",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/536008_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/tv-season/pilot/id271383858?i=271866344&uo=4&at=1000l3V2",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/tv-season/pilot/id271383858?i=271866344&uo=4&at=1000l3V2",
          "format": "HD",
          "price": 2.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&amp=&cdid=tvseason-2LA4CTEOrZM&gdid=tvepisode-PNxGMkcus_g&gl=US&hl=en&id=L2wfgMDGiBk",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&amp=&cdid=tvseason-2LA4CTEOrZM&gdid=tvepisode-PNxGMkcus_g&gl=US&hl=en&id=L2wfgMDGiBk",
          "format": "HD",
          "price": 2.49,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Breaking-Bad-Pilot/207577",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Breaking-Bad-Pilot/207577",
          "format": "HD",
          "price": 2.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.74a9f71f-3d5a-f492-23dc-3dfbc2404a24",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 54
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.74a9f71f-3d5a-f492-23dc-3dfbc2404a24",
          "format": "HD",
          "price": 2.99,
          "seasons": 5,
          "episodes": 54
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.74a9f71f-3d5a-f492-23dc-3dfbc2404a24",
          "format": "4K",
          "price": 3.99,
          "seasons": 5,
          "episodes": 54
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=PNxGMkcus_g",
          "format": "HD",
          "price": 2.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=PNxGMkcus_g",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxcmrfx",
          "format": "SD",
          "price": 1.99,
          "seasons": 5,
          "episodes": 54
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxcmrfx",
          "format": "HD",
          "price": 2.99,
          "seasons": 5,
          "episodes": 54
      },
      {
          "source_id": 203,
          "name": "Netflix",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "http://www.netflix.com/title/70143836",
          "format": "HD",
          "price": null,
          "seasons": 5,
          "episodes": 62
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/tv/Breaking-Bad-cmpQU2NNOEI5bnc9/Pilot-ak1weXpXOXB6K1AzeXhLdmhmUTl3Zz09",
          "format": "HD",
          "price": null,
          "seasons": 5,
          "episodes": 62
      }
  ]
}];


module.exports = {

  mockSearchResults: mockSearchResults,

}