var mockTrending = [
  {
    "id": 1434738,
    "title": "Titanic",
    "original_title": "Titanic",
    "plot_overview": "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
    "type": "movie",
    "runtime_minutes": 194,
    "year": 1997,
    "end_year": null,
    "release_date": "1997-11-18",
    "imdb_id": "tt0120338",
    "tmdb_id": 597,
    "tmdb_type": "movie",
    "genres": [
        7,
        14
    ],
    "genre_names": [
        "Drama",
        "Romance"
    ],
    "user_rating": 7.6,
    "critic_score": 82,
    "us_rating": "PG-13",
    "poster": "https://cdn.watchmode.com/posters/01434738_poster_w185.jpg",
    "backdrop": "https://cdn.watchmode.com/backdrops/01434738_bd_w780.jpg",
    "original_language": "en",
    "similar_titles": [
        1411293,
        1261570,
        136644,
        1325612,
        1409931,
        1189953,
        1390779,
        1321818,
        1385709,
        14126,
        1465849,
        1307725,
        1204879,
        161171,
        1250035,
        1177510,
        1115269,
        1133772,
        1138145,
        1395115,
        1406213,
        1381595,
        1292240,
        1415335,
        1231643
    ],
    "networks": null,
    "network_names": [],
    "relevance_percentile": 99.59,
    "trailer": "https://www.youtube.com/watch?v=CHekzSiZjrY",
    "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/638996_pthumbnail_320.jpg",
    "sources": [
        {
            "source_id": 391,
            "name": "Pluto TV",
            "type": "free",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://pluto.tv/on-demand/movies/titanic-1997-1-1?utm_medium=deeplink&",
            "format": "HD",
            "price": null,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 349,
            "name": "iTunes",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://itunes.apple.com/us/movie/titanic/id545892907?uo=4&at=10laHb",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 349,
            "name": "iTunes",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://itunes.apple.com/us/movie/titanic/id545892907?uo=4&at=10laHb",
            "format": "SD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 140,
            "name": "Google Play",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://play.google.com/store/movies/details/Titanic?id=jIhicnTgArM",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 140,
            "name": "Google Play",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://play.google.com/store/movies/details/Titanic?id=jIhicnTgArM",
            "format": "SD",
            "price": 2.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 307,
            "name": "VUDU",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.vudu.com/content/movies/details/content/14430",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 307,
            "name": "VUDU",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.vudu.com/content/movies/details/content/14430",
            "format": "SD",
            "price": 2.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 24,
            "name": "Amazon",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.60a9f73e-2d26-fd93-73d3-f087e87e6fca?",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 24,
            "name": "Amazon",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.60a9f73e-2d26-fd93-73d3-f087e87e6fca?",
            "format": "SD",
            "price": 2.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 398,
            "name": "Microsoft Store",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.microsoft.com/en-us/p/titanic-1997/8d6kgwzl58q1",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 398,
            "name": "Microsoft Store",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.microsoft.com/en-us/p/titanic-1997/8d6kgwzl58q1",
            "format": "SD",
            "price": 2.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 344,
            "name": "YouTube",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "http://www.youtube.com/watch?v=jIhicnTgArM",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 344,
            "name": "YouTube",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "http://www.youtube.com/watch?v=jIhicnTgArM",
            "format": "SD",
            "price": 2.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 442,
            "name": "DirecTV On Demand",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.directv.com/movies/Titanic-aDB5Q3NZQTFFSGJhb0hoM2UyNVNrUT09",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 443,
            "name": "Spectrum On Demand",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://ondemand.spectrum.net/movies/20056/titanic/",
            "format": "HD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 443,
            "name": "Spectrum On Demand",
            "type": "rent",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://ondemand.spectrum.net/movies/20056/titanic/",
            "format": "SD",
            "price": 3.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 349,
            "name": "iTunes",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://itunes.apple.com/us/movie/titanic/id545892907?uo=4&at=10laHb",
            "format": "HD",
            "price": 16.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 349,
            "name": "iTunes",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://itunes.apple.com/us/movie/titanic/id545892907?uo=4&at=10laHb",
            "format": "SD",
            "price": 12.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 140,
            "name": "Google Play",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://play.google.com/store/movies/details/Titanic?id=jIhicnTgArM",
            "format": "HD",
            "price": 16.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 140,
            "name": "Google Play",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://play.google.com/store/movies/details/Titanic?id=jIhicnTgArM",
            "format": "SD",
            "price": 12.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 307,
            "name": "VUDU",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.vudu.com/content/movies/details/content/14430",
            "format": "HD",
            "price": 16.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 307,
            "name": "VUDU",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.vudu.com/content/movies/details/content/14430",
            "format": "SD",
            "price": 14.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 24,
            "name": "Amazon",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.60a9f73e-2d26-fd93-73d3-f087e87e6fca?",
            "format": "HD",
            "price": 12.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 24,
            "name": "Amazon",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.60a9f73e-2d26-fd93-73d3-f087e87e6fca?",
            "format": "SD",
            "price": 12.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 398,
            "name": "Microsoft Store",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.microsoft.com/en-us/p/titanic-1997/8d6kgwzl58q1",
            "format": "HD",
            "price": 15.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 398,
            "name": "Microsoft Store",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.microsoft.com/en-us/p/titanic-1997/8d6kgwzl58q1",
            "format": "SD",
            "price": 14.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 344,
            "name": "YouTube",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "http://www.youtube.com/watch?v=jIhicnTgArM",
            "format": "HD",
            "price": 16.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 344,
            "name": "YouTube",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "http://www.youtube.com/watch?v=jIhicnTgArM",
            "format": "SD",
            "price": 12.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 442,
            "name": "DirecTV On Demand",
            "type": "buy",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.directv.com/movies/Titanic-aDB5Q3NZQTFFSGJhb0hoM2UyNVNrUT09",
            "format": "HD",
            "price": 16.99,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 26,
            "name": "Amazon Prime",
            "type": "sub",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.60a9f73e-2d26-fd93-73d3-f087e87e6fca?",
            "format": "HD",
            "price": null,
            "seasons": null,
            "episodes": null
        },
        {
            "source_id": 444,
            "name": "Paramount+",
            "type": "sub",
            "region": "US",
            "ios_url": "Deeplinks available for paid plans only.",
            "android_url": "Deeplinks available for paid plans only.",
            "web_url": "https://www.paramountplus.com/movies/titanic/GjggIcNk2C1sYQ_JG6j5LoKa7hxsQOzw/",
            "format": "HD",
            "price": null,
            "seasons": null,
            "episodes": null
        }
    ]
},
{
  "id": 1353260,
  "title": "Solaris",
  "original_title": "Solaris",
  "plot_overview": "A troubled psychologist is sent to investigate the crew of an isolated research station orbiting a bizarre planet.",
  "type": "movie",
  "runtime_minutes": 99,
  "year": 2002,
  "end_year": null,
  "release_date": "2002-11-27",
  "imdb_id": "tt0307479",
  "tmdb_id": 2103,
  "tmdb_type": "movie",
  "genres": [
      7,
      15,
      13
  ],
  "genre_names": [
      "Drama",
      "Mystery",
      "Science Fiction"
  ],
  "user_rating": 6.2,
  "critic_score": 66,
  "us_rating": "PG-13",
  "poster": "https://cdn.watchmode.com/posters/01353260_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/01353260_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      1583726,
      166918,
      186320,
      181564,
      1347464,
      1262733,
      181585,
      1122770,
      1156650,
      1382784,
      1134104,
      1125773,
      1309446,
      1493742,
      130599,
      1257102,
      160202,
      1373127,
      161906,
      117275,
      1235792,
      479986,
      1339673,
      1280420,
      1593239
  ],
  "networks": null,
  "network_names": [],
  "relevance_percentile": 98.67,
  "trailer": "",
  "trailer_thumbnail": "",
  "sources": [
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/movie/solaris/umc.cmc.58zo0g2o2ar4psaonor0zgxgu?playableId=tvs.sbd.9001%3A271628234",
          "format": "SD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/movie/solaris/umc.cmc.58zo0g2o2ar4psaonor0zgxgu?playableId=tvs.sbd.9001%3A271628234",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Solaris/8138",
          "format": "SD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Solaris/8138",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.f0a9f73a-550c-b7a0-93a3-812082513ce5",
          "format": "SD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.f0a9f73a-550c-b7a0-93a3-812082513ce5",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/solaris/8d6kgwzl5390",
          "format": "SD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/solaris/8d6kgwzl5390",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/movies/details/Solaris?gl=US&hl=en&id=9d1h1lKfqUo",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/results?search_query=Solaris%2Bmovie",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Solaris-R3pqblJ1R1ZWeWROUkZUa3BjalhxQT09",
          "format": "HD",
          "price": 3.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/movie/solaris/umc.cmc.58zo0g2o2ar4psaonor0zgxgu?playableId=tvs.sbd.9001%3A271628234",
          "format": "SD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/movie/solaris/umc.cmc.58zo0g2o2ar4psaonor0zgxgu?playableId=tvs.sbd.9001%3A271628234",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Solaris/8138",
          "format": "SD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Solaris/8138",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.f0a9f73a-550c-b7a0-93a3-812082513ce5",
          "format": "SD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.f0a9f73a-550c-b7a0-93a3-812082513ce5",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/solaris/8d6kgwzl5390",
          "format": "SD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/solaris/8d6kgwzl5390",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/movies/details/Solaris?gl=US&hl=en&id=9d1h1lKfqUo",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/results?search_query=Solaris%2Bmovie",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Solaris-R3pqblJ1R1ZWeWROUkZUa3BjalhxQT09",
          "format": "HD",
          "price": 14.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/movies/30452/solaris/",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 387,
          "name": "HBO MAX",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.hbomax.com/feature/urn:hbo:feature:GWSL-DwtrYK6-wgEAAABQ",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 385,
          "name": "HBO (Via Hulu)",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.hulu.com/movie/solaris-597ba70e-5684-4c66-95d5-2872b3e3c3be",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      }
  ]
},
{
  "id": 3159756,
  "title": "Euphoria",
  "original_title": "Euphoria",
  "plot_overview": "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
  "type": "tv_series",
  "runtime_minutes": 60,
  "year": 2019,
  "end_year": null,
  "release_date": "2019-06-16",
  "imdb_id": "tt8772296",
  "tmdb_id": 85552,
  "tmdb_type": "tv",
  "genres": [
      7
  ],
  "genre_names": [
      "Drama"
  ],
  "user_rating": 8.3,
  "critic_score": 78,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/03159756_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/03159756_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      3105822,
      397065,
      371931,
      389252,
      4142200,
      3162327,
      3105456,
      360347,
      540358,
      314163,
      3121411,
      3140097,
      398260,
      3106167,
      39844,
      1260183,
      3169554,
      338086,
      3142025,
      390217,
      381024,
      540761,
      314892,
      394665,
      3166382
  ],
  "networks": [
      1
  ],
  "network_names": [
      "HBO"
  ],
  "relevance_percentile": 99.79,
  "trailer": "https://www.youtube.com/watch?v=JjcfL8fbs7k",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/8024_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.4ab5abae-4504-6002-ad6a-3ee10e9cd0ee",
          "format": "HD",
          "price": 3.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.4ab5abae-4504-6002-ad6a-3ee10e9cd0ee",
          "format": "SD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&amp=&cdid=tvseason-S2RchsyyHk8.P&gdid=tvepisode-IumT6y9XrOI.P&gl=US&hl=en&id=XxKzCHkHuhx2Dr9X3548gA",
          "format": "HD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 10
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&amp=&cdid=tvseason-S2RchsyyHk8.P&gdid=tvepisode-IumT6y9XrOI.P&gl=US&hl=en&id=XxKzCHkHuhx2Dr9X3548gA",
          "format": "SD",
          "price": 1.99,
          "seasons": 2,
          "episodes": 10
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Euphoria-Special-Trouble-Dont-Last-Always/1672100",
          "format": "HD",
          "price": 3.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Euphoria-Special-Trouble-Dont-Last-Always/1672100",
          "format": "SD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=6UXHcH6DgA8",
          "format": "HD",
          "price": 2.99,
          "seasons": 1,
          "episodes": 1
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=6UXHcH6DgA8",
          "format": "SD",
          "price": 1.99,
          "seasons": 1,
          "episodes": 1
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/episode/pilot/umc.cmc.1u2zipg6j1dbkyr9085qnsq7b?playableId=tvs.sbd.9001%3A1473829375&showId=umc.cmc.6mdis9zh78p0ifdz7ti1ku0al",
          "format": "SD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/episode/pilot/umc.cmc.1u2zipg6j1dbkyr9085qnsq7b?playableId=tvs.sbd.9001%3A1473829375&showId=umc.cmc.6mdis9zh78p0ifdz7ti1ku0al",
          "format": "HD",
          "price": 3.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxmztmb",
          "format": "SD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxmztmb",
          "format": "HD",
          "price": 3.99,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 387,
          "name": "HBO MAX",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.hbomax.com/episode/urn:hbo:episode:GXKOAMQ3qNcJzwwEAAAAU",
          "format": "HD",
          "price": null,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/tv/Euphoria-R3U4VGlKcjZkcEdGby9GckxSaXJvUT09/Pilot-TC9vVUtDWEd4dlNLTXpJTFBKcUdnUT09",
          "format": "HD",
          "price": null,
          "seasons": 2,
          "episodes": 16
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/tv/hbo-max/16792512/euphoria/",
          "format": "HD",
          "price": null,
          "seasons": 2,
          "episodes": 16
      }
  ]
},
{
  "id": 3166889,
  "title": "Next in Fashion",
  "original_title": "Next in Fashion",
  "plot_overview": "Talented designers from around the world compete for $250,000 and the chance to become the next big thing in fashion.",
  "type": "tv_series",
  "runtime_minutes": 50,
  "year": 2020,
  "end_year": 2020,
  "release_date": "2020-01-29",
  "imdb_id": "tt10394770",
  "tmdb_id": 98805,
  "tmdb_type": "tv",
  "genres": [
      23
  ],
  "genre_names": [
      "Reality"
  ],
  "user_rating": 7.1,
  "critic_score": null,
  "us_rating": "TV-14",
  "poster": "https://cdn.watchmode.com/posters/03166889_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/03166889_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      378501,
      31122,
      3177500,
      313070,
      35416,
      383504,
      313071,
      341030,
      357947,
      3166510,
      364284,
      320406,
      397059,
      353853,
      3176806,
      347933,
      3155480,
      3109037,
      329246,
      351613,
      372565,
      347792,
      363963,
      360318,
      383503
  ],
  "networks": [
      248
  ],
  "network_names": [
      "Netflix"
  ],
  "relevance_percentile": 92.71,
  "trailer": "https://www.youtube.com/watch?v=a2W0ivtnXjY",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/262302_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 203,
          "name": "Netflix",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "http://www.netflix.com/title/81026300",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 10
      }
  ]
},
{
  "id": 1592806,
  "title": "Severance",
  "original_title": "Severance",
  "plot_overview": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
  "type": "tv_series",
  "runtime_minutes": 60,
  "year": 2022,
  "end_year": null,
  "release_date": "2022-02-17",
  "imdb_id": "tt11280740",
  "tmdb_id": 95396,
  "tmdb_type": "tv",
  "genres": [
      13,
      40
  ],
  "genre_names": [
      "Mystery",
      "Sci-Fi & Fantasy"
  ],
  "user_rating": 8.4,
  "critic_score": 90,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/01592806_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/01592806_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      3125661,
      3105068,
      3123483,
      3123551,
      325462,
      56018,
      3173896,
      538398,
      3173605,
      3130921,
      3106287,
      3122017,
      395040,
      3171235,
      380991,
      3166458,
      3161005,
      4143625,
      3168874,
      3125033,
      3155890,
      3121034,
      3112487,
      519773,
      541722
  ],
  "networks": [
      822
  ],
  "network_names": [
      "Apple TV"
  ],
  "relevance_percentile": 99.93,
  "trailer": "https://www.youtube.com/watch?v=xEQP4VVuyrY",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/638808_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 371,
          "name": "AppleTV+",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/episode/good-news-about-hell/umc.cmc.s80mx1ic96pu6ewupz8pfasf?at=1000l3V2&ct=app_tvplus&playableId=tvs.sbd.4000%3AVSEVR0560101&showId=umc.cmc.1srk2goyh2q2zdxcx605w8vtx",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 9
      }
  ]
},
{
  "id": 1496273,
  "title": "Dune",
  "original_title": "Dune",
  "plot_overview": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
  "type": "movie",
  "runtime_minutes": 155,
  "year": 2021,
  "end_year": null,
  "release_date": "2021-09-15",
  "imdb_id": "tt1160419",
  "tmdb_id": 438631,
  "tmdb_type": "movie",
  "genres": [
      15,
      2
  ],
  "genre_names": [
      "Adventure",
      "Science Fiction"
  ],
  "user_rating": 8.2,
  "critic_score": 79,
  "us_rating": "PG-13",
  "poster": "https://cdn.watchmode.com/posters/01496273_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/01496273_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      1154248,
      1339845,
      1406622,
      1115063,
      1359266,
      1398133,
      1154249,
      1359306,
      1359246,
      1184713,
      1450054,
      1325013,
      1359292,
      1292618,
      138100,
      1589918,
      1359256,
      1461996,
      1359310,
      1431650,
      1195859,
      1472957,
      1257217,
      1317301,
      166939
  ],
  "networks": null,
  "network_names": [],
  "relevance_percentile": 99.99,
  "trailer": "https://www.youtube.com/watch?v=76bpJ6o6n9s",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/639175_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "HD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "SD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "4K",
          "price": 24.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "HD",
          "price": 24.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "SD",
          "price": 24.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "HD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "SD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "HD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "SD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/movies/details/Dune?gl=US&hl=en&id=r9FqbC-kvqs.P",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=sQBn-pbJEH4",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/movies/16645155/dune/",
          "format": "HD",
          "price": 6.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/movies/16645155/dune/",
          "format": "SD",
          "price": 6.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Dune-b3F0QkFsd0trcUlHc0RYR3Q1d3l3dz09",
          "format": "4K",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "rent",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Dune-b3F0QkFsd0trcUlHc0RYR3Q1d3l3dz09",
          "format": "HD",
          "price": 5.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "HD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/1729967",
          "format": "SD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "4K",
          "price": 29.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "HD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2b431e55-20f9-4b0c-9bb2-be1f4bd469e6?",
          "format": "SD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "HD",
          "price": 9.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/movie/dune/id1585877256?uo=4&at=10laHb",
          "format": "SD",
          "price": 9.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "HD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/dune/8d6kgwxn4lnb",
          "format": "SD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/movies/details/Dune?gl=US&hl=en&id=r9FqbC-kvqs.P",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=sQBn-pbJEH4",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Dune-b3F0QkFsd0trcUlHc0RYR3Q1d3l3dz09",
          "format": "4K",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Dune-b3F0QkFsd0trcUlHc0RYR3Q1d3l3dz09",
          "format": "HD",
          "price": 19.99,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/movies/16645155/dune/",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Dune-b3F0QkFsd0trcUlHc0RYR3Q1d3l3dz09",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 387,
          "name": "HBO MAX",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.hbomax.com/feature/urn:hbo:feature:GYUjdLgBiJp5otAEAAAAJ",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      },
      {
          "source_id": 385,
          "name": "HBO (Via Hulu)",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.hulu.com/movie/dune-c5682975-40cf-4a49-93d4-af29bc930964",
          "format": "HD",
          "price": null,
          "seasons": null,
          "episodes": null
      }
  ]
},
{
  "id": 1581343,
  "title": "Tokyo Vice",
  "original_title": "Tokyo Vice",
  "plot_overview": "A first-hand account of the Tokyo Metropolitan Police beat following Jake Adelstein, an American journalist who embeds himself into the Tokyo Vice police squad to reveal corruption. Based on Jake Adelstein’s non-fiction book of the same name.",
  "type": "tv_series",
  "runtime_minutes": 57,
  "year": 2022,
  "end_year": null,
  "release_date": "2022-04-07",
  "imdb_id": "tt2887954",
  "tmdb_id": 90296,
  "tmdb_type": "tv",
  "genres": [
      5,
      7
  ],
  "genre_names": [
      "Crime",
      "Drama"
  ],
  "user_rating": 8,
  "critic_score": 80,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/01581343_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/01581343_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      3150320,
      3108916,
      3165490,
      56018,
      3177706,
      3180300,
      3105771,
      383654,
      3171721,
      3106287,
      4140426,
      542971,
      1258765,
      3118752,
      519468,
      3166139,
      3178957,
      3142025,
      3164356,
      3165148,
      3164730,
      3164445,
      3173605,
      3176091,
      3163373
  ],
  "networks": [
      1724
  ],
  "network_names": [
      "HBO Max"
  ],
  "relevance_percentile": 100,
  "trailer": "https://www.youtube.com/watch?v=daTQTQMLYgc",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/640394_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 387,
          "name": "HBO MAX",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.hbomax.com/episode/urn:hbo:episode:GYj5PgwXrfsPCDgEAAAH0",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 3
      }
  ]
},
{
  "id": 39718,
  "title": "Atlanta",
  "original_title": "Atlanta",
  "plot_overview": "Two cousins work through the Atlanta music scene in order to better their lives and the lives of their families.",
  "type": "tv_series",
  "runtime_minutes": 30,
  "year": 2016,
  "end_year": null,
  "release_date": "2016-09-06",
  "imdb_id": "tt4288182",
  "tmdb_id": 65495,
  "tmdb_type": "tv",
  "genres": [
      4,
      7
  ],
  "genre_names": [
      "Comedy",
      "Drama"
  ],
  "user_rating": 8.6,
  "critic_score": 94,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/039718_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/039718_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      3161727,
      376094,
      3175847,
      3134753,
      399588,
      3158330,
      3168874,
      38901,
      3175082,
      313568,
      3107530,
      3155995,
      3174612,
      367620,
      372535,
      3108965,
      385457,
      378337,
      358040,
      346623,
      352442,
      3180199,
      3117686,
      3125756,
      3162413
  ],
  "networks": [
      173
  ],
  "network_names": [
      "FX"
  ],
  "relevance_percentile": 99.18,
  "trailer": "https://www.youtube.com/watch?v=t72Pbqrkb28",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/638774_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/tv-season/the-big-bang/id1141140967?i=1146014337&at=10laHb",
          "format": "SD",
          "price": 1.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://itunes.apple.com/us/tv-season/the-big-bang/id1141140967?i=1146014337&at=10laHb",
          "format": "HD",
          "price": 2.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?id=xpPVEbSRL88&cdid=tvseason-pcquUSx8ukpKiBhdDm9tHw&gdid=tvepisode-L16NaGnOBlY",
          "format": "SD",
          "price": 1.99,
          "seasons": 2,
          "episodes": 21
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?id=xpPVEbSRL88&cdid=tvseason-pcquUSx8ukpKiBhdDm9tHw&gdid=tvepisode-L16NaGnOBlY",
          "format": "HD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 21
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/791920",
          "format": "SD",
          "price": 1.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/content/791920",
          "format": "HD",
          "price": 2.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.a8ab805a-0c65-e6e1-6689-8402baa6bfa6?",
          "format": "SD",
          "price": 1.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.amazon.com/gp/video/detail/amzn1.dv.gti.a8ab805a-0c65-e6e1-6689-8402baa6bfa6?",
          "format": "HD",
          "price": 2.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgx0n30wq",
          "format": "HD",
          "price": 2.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgx0n30wq",
          "format": "SD",
          "price": 1.99,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=L16NaGnOBlY",
          "format": "HD",
          "price": 2.99,
          "seasons": 2,
          "episodes": 21
      },
      {
          "source_id": 344,
          "name": "YouTube",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.youtube.com/watch?v=L16NaGnOBlY",
          "format": "SD",
          "price": 1.99,
          "seasons": 2,
          "episodes": 21
      },
      {
          "source_id": 157,
          "name": "Hulu",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "http://www.hulu.com/watch/3627c052-e817-4b78-8c71-9fbdde4e5e09",
          "format": "HD",
          "price": null,
          "seasons": 3,
          "episodes": 25
      },
      {
          "source_id": 442,
          "name": "DirecTV On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.directv.com/movies/Atlanta-aDV6MGZxOWp1RUMvUDByZ3NBS1cwUT09",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 4
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/tv/fx/13060983/atlanta/",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 5
      },
      {
          "source_id": 373,
          "name": "fuboTV",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://link.fubo.tv/al1%3Fv%3D1%26a%3Dplay%26t%3Dprogram%26pid%3DEP024673340027%26o%3D0&irmp=1993008&irad=599307",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 3
      },
      {
          "source_id": 122,
          "name": "FX",
          "type": "tve",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "http://www.fxnetworks.com/video/1188284483916",
          "format": "HD",
          "price": null,
          "seasons": 2,
          "episodes": 6
      },
      {
          "source_id": 10,
          "name": "ABC",
          "type": "tve",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://abc.com/shows/atlanta/episode-guide/season-03/episode-01-three-slaps/vdka26963737",
          "format": "HD",
          "price": null,
          "seasons": 1,
          "episodes": 4
      }
  ]
}
];

module.exports = {

  mockTrending: mockTrending

}